version: "3.9"
services:
  frontend:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=1
    command: "./start.sh"